apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: hoanghog/ts-test-app:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 3001 
          env:
          - name: redis_host
            value: "redis-service"
          resources: {}



