apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
data:
  config.yaml: |
    services:
      - name: example
        url: http://localhost:8181/v1/data

    labels:
      - example

    decision_logs:
      console: true
