apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        args:
        - "run"
        - "--server"
        - "--config-file=/config/config.yaml"
        - "--data-file=/data/users.json"
        volumeMounts:
        - mountPath: /config
          name: opa-config
        - mountPath: /data
          name: opa-data
      volumes:
      - name: opa-config
        configMap:
          name: opa-config
      - name: opa-data
        configMap:
          name: opa-data
