apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    app: pv1
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  hostPath:
    path: /Users/m1pro-hoang/temp/pv/vp1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  resources:
    requests:
      storage: 256Mi
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: pv1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: hoanghog/redis:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - name: db
              mountPath: /data
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: pvc1
